// Generated by SA Tools Struct Converter

#include "SADXModLoader.h"

TrialLevelListEntry TailsSubgames_list[] = {
	{ LevelIDs_SkyChase1, 0 },
	{ LevelIDs_SkyChase2, 0 },
	{ LevelIDs_IceCap, 2 },
	{ LevelIDs_SandHill, 0 },
	{ LevelIDs_TwinkleCircuit, 1 },
	{ LevelIDs_EggWalker, 0 }
};

TrialLevelList TailsSubgames = { arrayptrandlength(TailsSubgames_list) };

TrialLevelListEntry KnucklesSubgames_list[] = {
	{ LevelIDs_TwinkleCircuit, 2 },
	{ LevelIDs_Chaos6, 1 }
};

TrialLevelList KnucklesSubgames = { arrayptrandlength(KnucklesSubgames_list) };

TrialLevelListEntry AmySubgames_list[] = {
	{ LevelIDs_HedgehogHammer, 0 },
	{ LevelIDs_TwinkleCircuit, 3 },
	{ LevelIDs_Zero, 0 }
};

TrialLevelList AmySubgames = { arrayptrandlength(AmySubgames_list) };

TrialLevelListEntry GammaSubgames_list[] = {
	{ LevelIDs_TwinkleCircuit, 5 },
	{ LevelIDs_E101R, 0 }
};

TrialLevelList GammaSubgames = { arrayptrandlength(GammaSubgames_list) };

TrialLevelListEntry BigSubgames_list[] = {
	{ LevelIDs_TwinkleCircuit, 4 },
	{ LevelIDs_Chaos6, 0 }
};

TrialLevelList BigSubgames = { arrayptrandlength(BigSubgames_list) };

extern "C" __declspec(dllexport) void Init(const char *path, const HelperFunctions &helperFunctions)
{
	TrialSubgames[1] = TailsSubgames;
	TrialSubgames[2] = KnucklesSubgames;
	TrialSubgames[3] = AmySubgames;
	TrialSubgames[4] = BigSubgames;
	TrialSubgames[5] = GammaSubgames;
}

extern "C" __declspec(dllexport) const ModInfo SADXModInfo = { ModLoaderVer };